ORG 0000H
START:
MOV  A,#0		      ;设置地址偏移量
CALL FUNCENTER
MOV  A,#1		      ;设置地址偏移量
CALL FUNCENTER
MOV  A,#2		      ;设置地址偏移量
CALL FUNCENTER
MOV  A,#3		      ;设置地址偏移量
CALL FUNCENTER
LJMP $
FUNCENTER:
ADD  A,ACC     		    ;AJMP为二字节指令，地址偏移量*2
MOV  DPTR,#FUNCTAB	    ;设置基址
JMP  @A+DPTR		    ;跳转到目标地址
FUNCTAB:
AJMP FUNC0
AJMP FUNC1
AJMP FUNC2
AJMP FUNC3
FUNC0:MOV 30H,#0
RET
FUNC1:MOV 31H,#1
RET
FUNC2:MOV 32H,#2
RET
FUNC3:MOV 33H,#3
RET
END
