/* Main.c file generated by New Project wizard
 *
 * Created:   ÷‹“ª 5‘¬ 28 2018
 * Processor: AT89C52
 * Compiler:  IAR for 8051 (C)
 */

#include <ioAT89C52.h>

#define P21 (P2_bit.P2_1)
#define P22 (P2_bit.P2_2)
#define P23 (P2_bit.P2_3)
#define P24 (P2_bit.P2_4)

#define P33 (P3_bit.P3_3)
#define P34 (P3_bit.P3_4)
#define P35 (P3_bit.P3_5)
#define P36 (P3_bit.P3_6)
#define P37 (P3_bit.P3_7)

void delay(int);

void main()
 { 
	 P21 = 0;
	 P22 = 1;
	 P23 = 1;
	 P24 = 1;
	 P33 = 1;
	 P34 = 1;
	 P35 = 1;
	 P36 = 1;
	 P37 = 1;
   // Write your code here
   while (1){
      if(!P35){
		  P22 = !P22;
		  while(!P35);
		  if(P22 == 1){
			  P21 = 0;
			  P23 = 1;
			  continue;
		  }
	  }
	  if(!P34 && !P22){
		  P23 = 0;
		  while(!P34);
	  }
	  if(!P36 && !P22){
		  P23 = 1;
		  while(!P36);
	  }
	  if(!P33){
		  P24 = !P24;
		  while(!P33);
	  }
	  delay(1000);
   }
 }

 void delay(int i){
	 while(i--);
 }
 
 
 