/* Main.c file generated by New Project wizard
 *
 * Created:   ÷‹“ª 5‘¬ 21 2018
 * Processor: 80C52
 * Compiler:  IAR for 8051 (C)
 */

#include <io80C52.h>
void main(void)
 { 
   while(1)
    { ;
    }
 }